name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Generate Apk file 
      if: always()
      run: ./gradlew assembleDebug

    - name: Upload AAR files
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: artifacts.zip
        path: |
          app/build/outputs/apk/debug/app-debug.apk
          dog_network/build/outputs/aar   
